-- create VIDEOSTART_RAW to load the raw file
CREATE TABLE VIDEOSTART_RAW (
   DATETIME VARCHAR(30),
   VIDEOTITLE VARCHAR(200),
   EVENTS VARCHAR(150)
);
-- create VIDEOSTART_DLT to store the data after data transfermation
CREATE TABLE VIDEOSTART_DLT (
   DATETIME TIMESTAMP (6) NOT NULL,
   PLATFORM VARCHAR(200) NOT NULL,
   SITE VARCHAR(200) NOT NULL,
   VIDEO VARCHAR(200) NOT NULL
);
-- create FACTVIDEOSTART to store the transaction data
CREATE TABLE FACTVIDEOSTART (
   DATETIME_SKEY VARCHAR(12) NOT NULL,
   PLATFORM_SKEY INT NOT NULL,
   SITE_SKEY INT NOT NULL,
   VIDEO_SKEY INT NOT NULL,
   DB_INSERT_TIMESTAMP TIMESTAMP(6) NOT NULL
);
-- create DIMDATE_DLT to store DATETIME data from raw file
CREATE TABLE DIMDATE_DLT (
   DATETIME VARCHAR(12) NOT NULL,
   CONSTRAINT dimdate_dlt_pk PRIMARY KEY (DATETIME)
);
-- create DIMPLATFORM_DLT to store PLATFORM data from raw file
CREATE TABLE DIMPLATFORM_DLT (
   PLATFORM VARCHAR(200) NOT NULL,
   CONSTRAINT dimplatform_dlt_pk PRIMARY KEY (PLATFORM)
);
-- create DIMSITE_DLT to store SITE data from raw file
CREATE TABLE DIMSITE_DLT (
   SITE VARCHAR(200) NOT NULL,
   CONSTRAINT dimsite_dlt_pk PRIMARY KEY (SITE)
);
-- create DIMVIDEO_DLT to store VIDEO data from raw file
CREATE TABLE DIMVIDEO_DLT (
   VIDEO VARCHAR(200) NOT NULL,
   CONSTRAINT dimvideo_dlt_pk PRIMARY KEY (VIDEO)
);
-- create dimension table DIMDATE
CREATE TABLE DIMDATE (
   DATETIME_SKEY VARCHAR(12) NOT NULL,
   CONSTRAINT dimdate_pk PRIMARY KEY (DATETIME_SKEY)
);
-- create dimension table DIMPLATFORM
CREATE TABLE DIMPLATFORM (
   PLATFORM_SKEY INT NOT NULL AUTO_INCREMENT,
   PLATFORM VARCHAR(200) NOT NULL,
   CONSTRAINT dimplatform_pk PRIMARY KEY (PLATFORM_SKEY)
);
-- initially insert one record
INSERT INTO DIMPLATFORM
VALUES (-1, 'Unknown');
-- create dimension table DIMSITE
CREATE TABLE DIMSITE (
   SITE_SKEY INT NOT NULL AUTO_INCREMENT,
   SITE VARCHAR(200) NOT NULL,
   CONSTRAINT dimsite_pk PRIMARY KEY (SITE_SKEY)
);
-- initially insert one record
INSERT INTO DIMSITE
VALUES (-1, 'Unknown');
-- create dimension table DIMVIDEO
CREATE TABLE DIMVIDEO (
   VIDEO_SKEY INT NOT NULL AUTO_INCREMENT,
   VIDEO VARCHAR(200) NOT NULL,
   CONSTRAINT dimvideo_pk PRIMARY KEY (VIDEO_SKEY)
);
-- create fact table FACTVIDEOSTART
CREATE TABLE FACTVIDEOSTART (
   DATETIME_SKEY TIMESTAMP (6) NOT NULL,
   PLATFORM_SKEY VARCHAR(200) NOT NULL,
   SITE_SKEY VARCHAR(200) NOT NULL,
   VIDEO_SKEY VARCHAR(200) NOT NULL
);