INSERT INTO DIMDATE_DLT
SELECT DATE_FORMAT(DATETIME, '%Y-%m-%d %T')
FROM VIDEOSTART_DLT
GROUP BY DATE_FORMAT(DATETIME, '%Y-%m-%d %T')
ORDER BY DATE_FORMAT(DATETIME, '%Y-%m-%d %T');
INSERT INTO DIMPLATFORM_DLT
SELECT PLATFORM
FROM VIDEOSTART_DLT
GROUP BY PLATFORM
ORDER BY PLATFORM;
INSERT INTO DIMSITE_DLT
SELECT SITE
FROM VIDEOSTART_DLT
GROUP BY SITE
ORDER BY SITE;
INSERT INTO DIMVIDEO_DLT
SELECT VIDEO
FROM VIDEOSTART_DLT
GROUP BY VIDEO
ORDER BY VIDEO;