INSERT INTO FACTVIDEOSTART
SELECT DD.DATETIME_SKEY,
    DP.PLATFORM_SKEY,
    DS.SITE_SKEY,
    DV.VIDEO_SKEY,
    SYSTIMESTAMP
FROM VIDEOSTART_DLT VSD
    LEFT JOIN DIMDATE DD ON DATE_FORMAT(VSD.DATETIME, '%Y-%m-%d %T') = DD.DATETIME_SKEY
    LEFT JOIN DIMPLATFORM DP ON VSD.PLATFORM = DP.PLATFORM
    LEFT JOIN DIMSITE DS ON VSD.SITE = DS.SITE
    LEFT JOIN DIMVIDEO DV ON VSD.VIDEO = DV.VIDEO;